### ISSUE TITLE
Will lc-12 also be supported

### ISSUE THREAD

**Issue by mruiter** [athombv/com.danfoss#1]
Will lc-12 also be supported.
Lots of the little bit older lc12s are out there. My house for example has 5 lc12 and 4 lc13
The difference in the driver to support it would not be that big i guess

**Comment by RobinBol** [comment]
We do not have one laying around here, but you could try to change the productId to match with the lc-12, the functionality will indeed be very likely similar to lc-13.

**Comment by mruiter** [comment]
lc12 is confirmed working. the device id is already in the driver. so lc13 is also lc12

**Comment by RobinBol** [comment]
Thanks for letting us know!
