### ISSUE TITLE
Cannot pair since 1.1.2

### ISSUE THREAD

**Issue by wallin** [athombv/com.danfoss#11]
Since the upgrade to 1.1.2 my existing LC-13 pairings show blank values for temperature and battery level. New devices cannot be added, since app says that "connection was lost" during pairing.

This worked fine in app version 1.1.0

My LC-13:s has firmware 1.01

**Comment by RobinBol** [comment]
When do you see "connection was lost"? Could you post a screenshot? Have you tried resetting the device?

**Comment by wallin** [comment]
Hey. I actually returned Homey since I filed this issue, so I can't provide any more information. You may close this issue

**Comment by RobinBol** [comment]
Ok, thanks for your response!
