### ISSUE TITLE
Danfoss RS 

### ISSUE THREAD

**Issue by lazerthomas** [athombv/com.danfoss#12]
I got hold of a couple of Danfoss RS (Roomsensors) a few days ago, and when adding those to homey I have to add them as generic Z-wave device. The Danfoss app does not recognize them. Added as generic Z-wave they come to no use. Is there any chance the danfoss app will be updated in the near future?
Here is a link to a screendump from homey that I posted on https://forum.athom.com
https://forum.athom.com/uploads/editor/pk/yw4u2xwl7q9d.png

**Comment by RobinBol** [comment]
We do not have these devices on our roadmap as of yet, you could try to find a developer on the Athom forum instead in the meanwhile.

**Comment by bvdbos** [comment]
Seeing the "GENERIC_TYPE_NON_INTEROPERABLE" I wonder if this possible?

**Comment by RobinBol** [comment]
My guess is that is just a rebrand of the (already implemented) Devolo Room Thermostat: https://apps.athom.com/app/com.devolo

**Comment by RobinBol** [comment]
Moved issue to main issue tracker: https://github.com/athombv/homey/issues/2555
