### ISSUE TITLE
Battery drain

### ISSUE THREAD

**Issue by Rob-Houweling** [athombv/com.danfoss#13]
I replaced the batteries last week and to my surprise the battery level is already down to 60% or less.
This way I need to replace the batteries every 3 weeks...

**Comment by RobinBol** [comment]
It might be that the device calculates the charge not correctly. Just see how the charge develops over a longer period of time.

Did you change some of the device settings? Polling interval or wake up interval for example?

**Comment by mruiter** [comment]
I dont have the drain anymore with the update SDKv2 i just pushed tru a pull

**Comment by RobinBol** [comment]
The PR was just published in the beta channel, please let us know if this resolves your issue!

**Comment by RobinBol** [comment]
The app was published in stable, so the issue should be resolved, if not, please leave a comment!
