### ISSUE TITLE
Enable/Disable child protection mode

### ISSUE THREAD

**Issue by BasKiers** [athombv/com.danfoss#15]
From a support ticket:

"Dear all, the current app for Danfoss is in Beta and works for me, what I did not found is the option to activate the child protection mode. Is this feature implemented and how do I activate it, if it's not yet included, may I ask to add it. Many thanks."

**Comment by BasKiers** [comment]
Usecases would probably need implementation in a flow to turn Child Protection on/off automatically.

**Comment by carmei** [comment]
Dear Robin, integration within flows is one enhancement, additional it would be nice if the option could be enabled manually within the settings. Many thanks

**Comment by RobinBol** [comment]
Moved issue to main issue tracker: https://github.com/athombv/homey/issues/2554
