### ISSUE TITLE
LC-13 seems not to wake up / recieve Homeys commands without manually wake up & Device Card settings are not being saved.

### ISSUE THREAD

**Issue by peaoo** [athombv/com.danfoss#2]
Hey I tested the App, here are the problems that I found:
- I had to remove my Danfoss two times from Homey. A single remove did not allow to enter the pairing process (not app related)
- When I change the Temperature in the Device Card and reopen the card it has not been saved.
- The thermostat seem not to recieve updated setpoint without manually push the lower button on the thermostat.  I changed  the wakeup intervall (and woke it manually up to recieve the changes) but it didn't help.
- The thermostats show following icons (blink) until I push the "pair button". Then the vanish and the setpoint is recieved from Homey. When I wake the thermostat up again the Icons are there again.
  ![danfoss](https://cloud.githubusercontent.com/assets/17235241/19360152/8e5b97be-917d-11e6-83c6-c68872febb4c.png)

For me it seems like the thermostat is only waking up when I push the button.

**Comment by RobinBol** [comment]
The thermostat is waking up at the specified wake up interval, that is why the temperature in the device card isn't updating; it is not saved on the device. When you change the temperature the command will be queued until the device wakes up, then it will send the command and change the temperature value in Homey. Until it has been received by the device, the temperature isn't actually set so it would be an incorrect view of the device state if we save the temperature directly.

If the device really is not receiving commands, even after the wake up interval has definitely expired, changes are that Homey is too far away from the device, or the mesh network is not optimal. Placing Homey closer and testing some commands can identify the cause of this problem.
