### ISSUE TITLE
Device shows error after successfull connect.

### ISSUE THREAD

**Issue by Vortjong** [athombv/com.danfoss#5]
Paring a danfoss LC-13 works fine. After a while the devices shows an error E5 on it's display and it is not controlling the water flow correctly (which off course is not caused by homey). According to the documentation, the E5 is caused by the control system, in this case Homey:
"The thermostat is not receiving the expected replies from the control system. Check that you have a Z-wave certified controller running and it has the necessary functionality to control the thermostat (see “Technical requirements”)."

**Comment by mike9011** [comment]
Same issue here, worked for a couple of hours. Now E5 error.

**Comment by Rob-Houweling** [comment]
Same issue here with the 1.0.1 firmware.
Pairing works fine but after a while all of my (6) LC13s show the E5 error.

**Comment by RobinBol** [comment]
Thanks for reporting, this issue will be continued here: https://github.com/athombv/homey/issues/1054
