### ISSUE TITLE
Request - Battery level

### ISSUE THREAD

**Issue by Rob-Houweling** [athombv/com.danfoss#7]
Is it possible to add the battery level of the thermostat in the flows? I would like homey to inform me if there is a thermostat of which the battery is almost empty.

**Comment by RobinBol** [comment]
This is already possible, there is a flow trigger for "De batterijwaarschuwing gaat aan" or "The battery alarm turned on" you can not read the exact level of the battery but this flow will trigger when the device thinks it is almost out of juice.

**Comment by Rob-Houweling** [comment]
Sorry, but where can I find this flow trigger? If I add the thermostat to the IF column I only get "The temperature has changed". No other options are available.

![image](https://cloud.githubusercontent.com/assets/5127988/23215452/b8b06aba-f912-11e6-8f5b-4c4b91fc9b49.png)

**Comment by RobinBol** [comment]
Apologies, it seems that functionality was still only local on my machine, just pushed an update to the app store!

**Comment by Rob-Houweling** [comment]
:) Cool, thanks!
