### ISSUE TITLE
Danfoss valve shows as Unknown Z-Wave device

### ISSUE THREAD

**Issue by acekrystal** [athombv/com.danfoss#9]
When I try to pair a Danfoss thermostat valve (version 014G0002 1.06) homey successfully pairs with it, but then tells me there is no app recognized for this z-wave device.

It then gets added as basic / unknown z-wave device.

Tryed multiple things already like repairing, reinstalling danfoss app, trying other apps that support danfoss. 

I think I have a early version, I see a list of devices here : https://www.domotiga.nl/projects/domotiga/wiki/Devices_ZWave_Danfoss_Radiator_Thermostat, where this seems to have software version 1.06 (actually version 2.06)

added a screenshot of my device info: 
![image](https://cloud.githubusercontent.com/assets/8919338/21981944/33ea43ae-dbea-11e6-8a39-2f51994fc3fc.png)

**Comment by RobinBol** [comment]
Sorry for the late response, I added you device ids a while back (https://github.com/athombv/com.danfoss/commit/a0133bb7884820d340185f5f617d30c12e8ce4f0) could you try to re-pair the device with the updated app? If it doesn't work, please re-open this issue, else I'll see it as resolved!
